# Frontend Dockerfile
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 5175
CMD ["sh", "-c", "VITE_PROXY_TARGET=http://185.183.35.80:3003 npm run dev -- --port 5175 --host 0.0.0.0"]
