version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: spiderhome_backend
    environment:
      - PORT=3003
      - DB_HOST=185.183.35.80
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASSWORD=StrongPass123
      - DB_NAME=sp_base
      - NODE_ENV=production
    ports:
      - "3003:3003"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: spiderhome_frontend
    environment:
      - VITE_PROXY_TARGET=http://185.183.35.80:3003
    depends_on:
      - backend
    ports:
      - "5175:5175"
    restart: unless-stopped
